### ISSUE TITLE
이런 재귀를 사용해보지 않겠는가(How about using this kind of recursion)

### ISSUE THREAD

**Issue by phillyai** [wlzla000/HelloWorld_C#1]
quicksort [] = []
quicksort (x:xs) = quicksort [a | a <- xs, a <= x] ++ [x] ++ quicksort [a | a <- xs, a > x]

하스켈 코드인데 이런 식으로 해보는건 어떰?
자바로 이렇게 짜본건 있는데 C로 짜보면 어떨지 궁금함

그리고 이름이 왜 헬로월든데 내용은 퀵소트야

**Comment by wlzla000** [comment]
I cannot understand the code..

**Comment by phillyai** [comment]
퀵소트 함수는 배열을 인자로 받고 소트된 배열을 리턴함

**Comment by wlzla000** [comment]
A quicksort function that accepts arrays as the parameters and returns a sorted array?
As you know, C does not have any garbage collector.
What you are saying needs a lot of memory allocations and deallocations (which have to be manually performed).
It might occur a kind of performance problem..
